### ISSUE TITLE
using both pgbouncer and pgpool buildpacks in series

### ISSUE THREAD

**Issue by gregorykan** [sobrinho/heroku-buildpack-pgpool#1]
hi there @sobrinho, first of all i want to say thanks so much for this buildpack! we've seen immense performance gains in our application because of your work.

i wanted to ask, is there any way to use both pgpool and pgbouncer buildpacks on the dyno?

**Comment by sobrinho** [comment]
Hi there! Thank you!

I had success doing that in a customer application but using a fork of pgbouncer buildpack to support connecting to pgpool, see https://github.com/heroku/heroku-buildpack-pgbouncer/pull/68.

All you have to do is configure pgpool to connect to the pgbouncer instead of connecting directly to the database, and keep your application connecting to the pgpool, i.e.:

```
app -> pgpool -> pbbouncer -> database
```
