### ISSUE TITLE
missing records issue

### ISSUE THREAD

**Issue by gregorykan** [sobrinho/heroku-buildpack-pgpool#3]
hi again @sobrinho, thanks so much for your prompt responses to my other questions.

as mentioned, we've seen massive improvements in performance overall.

however, we've also noticed that a small percentage of post-write read operations are failing because the newly-written records are 'not found'. i presume that the follower databases might be lagging behind.

to be more specific, this has to do with `POST` requests, where the `write` operation is successful, but the consequent `read` operation to return the newly persisted record is failing. querying for the same record a moment later is successful.

is this something that you've encountered before? i'm aware that this may not be directly related to pgpool/your buildpack, and perhaps has to do with heroku's implementation of follower catch-ups etc. but on the off chance that you do know about it, i thought i might ask.

thanks again!

**Comment by sobrinho** [comment]
Hi there!

Yeah, I have seen this before and there are a few options to work around that (you can pick one or more than one depending on the case):

1. You can avoid immediately reading the record right after writing, like redirecting to the index page instead of the show page and showing something like "You record will be available in a couple seconds" or something like that
2. If you are working in an SPA, similar behavior is possible to do with an optimistic interface
3. You can flag the user session to keep reading from master until the next request or for a couple minutes
4. You can compare master against slaves to make sure that they are updated

The 3rd option is the more complicated one since you are going to need a flag in the user session and manage connections manually.

It makes the application aware that there are followers and that they might be outdated in specific actions, what makes everything more complex.

The 4th option is even more complex since you are going to compare the lag between the two or more databases and define some algorithm like "I can accept at most 10 commits or 10 minutes behind master before switching back to read from master".

Another option I did in the past was like persisting some data in the localStorage to avoid stale data from the follower, like when you delete a record you can persist this status to the front-end and avoid showing this record even when the back-end returns it.

You can do the same using cookies, session or even a Redis database for that.

It all depends in your needs, you may need to use a combination of all of these options! :)

Btw, I remember that GitLab published a long article about that in the past but I haven't found it right now.

They explained the same issue and similar fixes for that.
